---
 - name: Playbook to update Fortinet devices
   hosts: all
   strategy: free
   tasks:
     - name: Update fortigates
       ansible.builtin.shell: /opt/vyatta/sbin/vyatta-cfg-yaml --update
       register: command_result
       failed_when: command_result.rc != 0
     - name: Display command output
       ansible.builtin.debug:
         msg: "{{ command_result.stdout_lines }}"
       when: command_result.stdout_lines is defined
     - name: Reboot system
       ansible.builtin.reboot:
       when: command_result.stdout_lines is defined
       register: reboot_status
       failed_when: reboot_status.rc != 0
     - name: Display reboot_status
       ansible.builtin.debug:
         msg: "{{ reboot_status.stdout_lines }}"
       when: reboot_status.stdout_lines is defined
     - name: Wait for connection
       ansible.builtin.wait_for_connection: timeout

