- name: Get mdadm status and send an email
  hosts: all
  tasks:
  - name: MDADM checks
    become: yes
    command: >
     mdadm -D /dev/md0 
    register: md_status

  - name: Send an email if there is a failure registered
    mail:
     host: 127.0.0.1
     port: 25
     to: uzajc@hotmail.com
     from: mrszajc@bigpond.com
     subject: Ansible MDADM Alert!!!
     body: |
      This is an ansible test email from {{ ansible_hostname }}
      Mdadm status:
      {{ md_status }}
    delegate_to: localhost
    when: '"FAILURE" in md_status'