- name: Get mdadm status and send an email
  hosts: all
#  module: community.general.mail
  tasks:
  - name: MDADM checks
    become: yes
    command: >
     mdadm -D /dev/md0 
    register: md_status

  - name: Send an email if there is a failure registered
    mail:
     host: 192.168.83.3
     port: 25
     to: uzajc@hotmail.com
     from: mrszajc@bigpond.com
<<<<<<< HEAD
     subject: Ansible Test
=======
     subject: Ansible MDADM Alert!!!
>>>>>>> d728b698c3ab46221d9863ea143c8e4fefbeedbb
     body: |
      This is an ansible test email from {{ ansible_hostname }}
      Mdadm status:
      {{ md_status }}
<<<<<<< HEAD
    delegate_to: localhost
    when: '"FAILURE" in md_status'
=======
    delegate_to: 127.0.0.1
    when: '"FAILURE" in md_status'
>>>>>>> d728b698c3ab46221d9863ea143c8e4fefbeedbb
