---
- name: Update mikrotik firmware
  hosts: mikrotik
  gather_facts: false
  tasks:
  - name: Write the new ssh keys known hosts
    connection: local
    shell: "ssh-keyscan -H {{ inventory_hostname }} >> ~/.ssh/known_hosts"
    delegate_to: localhost
  - name: Check if updates are available
    community.routeros.command:
      commands: 'system/package/update/check-for-updates'
    register: update_check
  - name: show Results
    ansible.builtin.debug:
     var: update_check
#   - name: email the Boss
#     community.general.mail:
#      host: 192.168.83.3
#      port: 25
#      to: uzajc@hotmail.com
#      from: mrszajc@bigpond.com
#      subject: Mikrotik Update Notice
#      body: |
#       This is an ansible generated email from Mikrotik update play
#       Update check pre-run:
#       {{ update_check }}
#       Update check post pre-run:
# #      {{ update_check_post }}
#     delegate_to: 127.0.0.1
#    when: '"New version is available" in update_check'




  #- name: backup router configuration

  # - name: Perform router update
  #   community.routeros.command:
  #     commands: 'system/package/update/ install'
  #   when: update_check.stdout.find('New version is available') != -1
  # - name: Do i have to restart router?
  # - name: wait for router to be online
  # - name: Check for udpates again
  #   community.routeros.command:
  #     commands: 'system/package/update/check-for-updates'wait_for:
  #   register: update_check_post
