---
- name: Update mikrotik firmware
  hosts: mikrotik
  gather_facts: false
  vars:
   backup_dir: "/home/uzajc/ansible/backup"
  tasks:

  - name: Backup
    ansible.builtin.copy:
      content: "{{ export.stdout }}"
      dest: "{{ backup_dir }}/{{ inventory_hostname }}/{{ inventory_hostname }}_config.{{ lookup('pipe', 'date +%Y-%m-%d@%H:%M:%S') }}"
    delegate_to: localhost
    

  - name: Wait for host to come back online
    wait_for_connection:
      delay: 30
      timeout: 300
    
  - name: Inform version
    uri:
      url: "http://192.168.1.89:70/zajcnet-notif"
      method: POST
      body: "{{ ansible_host }} updated"
#    when: '"New version is available" in update_check'
    # when: update_check.stdout is search('New version is available')

