---
- name: Update mikrotik firmware
  hosts: mikrotik
  gather_facts: false
  vars:
   backup_dir: "/home/uzajc/ansible/backup"
  tasks:
  
  # - name: Export
  #   community.routeros.command:
  #    commands: '/export'
  #   register: export

    
  # - name: Backup
  #   ansible.builtin.copy:
  #     content: "{{ export.stdout }}"
  #     dest: "{{ backup_dir }}/{{ inventory_hostname }}/{{ inventory_hostname }}_config.{{ lookup('pipe', 'date +%Y-%m-%d@%H:%M:%S') }}"
  #   delegate_to: localhost

  # - name: Update Router OS
  #   community.routeros.command:
  #    commands: '/system package update install'
       

  # - name: Wait for host to come back online
  #   wait_for_connection:
  #     delay: 30
  #     timeout: 300
      
  # - name: Update Router Firmware
  #   community.routeros.command:
  #    commands: ' :execute {/system/routerboard/upgrade}'

  # - name: Reboot Router
  #   community.routeros.command:
  #    commands: ':execute {/system reboot}'

  # - name: Wait for host to come back online
  #   wait_for_connection:
  #     delay: 30
  #     timeout: 300 
  - name: capture results
    community.routeros.command:
     commands: 'system/package/update/check-for-updates'
    register: software_version 
    
  - name: Inform version
    uri:
      url: "http://192.168.1.89:70/zajcnet-notif"
      method: POST
      body: "{{ ansible_host }} updated \n {{ software_version }} "
#    when: '"New version is available" in update_check'
    # when: update_check.stdout is search('New version is available')

