---
- name: Docker prunning
  hosts: hp
  tasks:
  - name: Prune containers and images
    community.docker.docker_prune:
      containers: true
#      containers_filters:
#        dangling: true
      images: true
      images_filters:
        dangling: true
      builder_cache: true
