---
- name: Docker prunning
  hosts: hp
  tasks:
  - name: Prune containers and images
    community.docker.docker_prune:
      containers: true
      images: true
      networks: true
#      volumes: true
      builder_cache: true
