---
- name: Update APT cache
  hosts: all
  become: yes
  tasks:
    - name: Apt Cache Stuff
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Remove dependencies that are no longer required - First Run
      apt:
        autoremove: yes
    - name: Apt-get upgrade
      apt:
        upgrade: yes
    - name: Remove dependencies that are no longer required - Second Run
      apt:
        autoremove: yes
        
    - name: Check if a reboot is required
      stat: path=/var/run/reboot-required get_md5=no
      register: reboot_flag

    - name: Reboot the server is needed
      reboot:
        reboot_timeout: 300
      when: reboot_flag.stat.exists == true

    - debug:
        msg: "Server is back up and running"
