- hosts: redhat
  gather_facts: false
  tasks:
    - block:
        - wait_for_connection:
            sleep: 1
            timeout: 10
          register: host_status
      rescue:
        - debug:
            msg: "{{ inventory_hostname }} not connected. End of host."
        - meta: clear_host_errors
        - meta: end_host

    - debug:
        # msg: "{{ inventory_hostname }} is running"
        var: host_status
