---
- hosts: redhat
  gather_facts: no
  tasks:

- name: verify connections on Red Hat servers
  wait_for:
    host: redhat
    port: 22
    delay: 5
  delegate_to: localhost
  register: ping_result
    #delegate_to: localhost
- name: debug stuff
  ansible.builtin.debug:
    var: ping_result
