---
- name: Check if the hosts are online and run Wake-on-LAN if they are not
  hosts: localhost
  gather_facts: no
  vars:
    hosts_to_check:
      - name: rhel
        ip: 192.168.1.133
        mac: 54:BF:64:5E:87:61
      - name: fedora
        ip: 192.168.1.135
        mac: D8:9E:F3:48:4B:01
  tasks:
    - name: Check if the hosts are online
      wait_for:
        host: "{{ item.ip }}"
        port: 22
        timeout: 10
      register: result
      loop: "{{ hosts_to_check }}"
      ignore_errors: yes

    - name: Wake-on-LAN if any host is not online
      when: item.failed
      delegate_to: localhost
      community.general.wakeonlan:
        mac: "{{ item.item.mac }}"
      with_items: "{{ result.results }}"

    - name: Now sit and wait
      ansible.builtin.wait_for_connection:
        timeout: 300
        delay: 10
        host: "{{ item.item.ip }}"
      with_items: "{{ result.results }}"
      when: item.failed
