---
- name: Check if the host is online and run Wake-on-LAN if it's not
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check if the host is online
      wait_for:
        host: "{{ item }}"
        port: 22
        timeout: 10
      register: result
      with_items:
        - rhel
        - fedora
    # debug: 
    # var: result

    # - name: Wake-on-LAN if the host is not online
    #   when: result.failed
    #   local_action: command wakeonlan {{ mac_address }}
