---
- hosts: redhat
  gather_facts: no
  tasks:

  - name: Test reachability to redhat servers
    ansible.builtin.ping:
    #   dest: "{{ item }}"
    # with_items:
    #   - rhel
    #   - fedora
    register: ping_result
    #delegate_to: localhost

  - name: debug stuff
    ansible.builtin.debug:
      var: ping_result
