---
##- hosts: redhat
- hosts: rhel
  become: yes
  
  tasks:

  # - name: Check packages to upgrade
  #   dnf:
  #     list: updates
  #   register: packages

  # - name: Show packages to upgrade
  #   debug:
  #     msg: >-
  #         {%- set output=[] -%}
  #         {%- for p in packages.results -%}
  #         {{ output.append('%-40s' % (p.name ~ '-' ~ p.version) ~ ' | repo: ' ~ p.repo) }}
  #         {%- endfor -%}
  #         {{ output }}

  - name: Apply updates using dnf module.
    dnf:
      name: '*'
      state: latest
      update_cache: true
      update_only: true
    register: dnfupdate_status


  # - name: Install the latest version of dnf utils
  #   ansible.builtin.dnf:
  #     name:
  #     - dnf-utils
  #     state: latest

  - name: Remove packages not needed anymore
    dnf:
     autoremove: true

  - name: Check if needs restarting
    ansible.builtin.command: '/usr/bin/needs-restarting -r'
    register: needs_restarting
    failed_when: false

  - name: Inform updates are done
    uri:
      url: "http://192.168.1.89:70/zajcnet-notif"
      method: POST
      body: "{{ ansible_hostname }} patched: \n {{ dnfupdate_status.stdout }}"
    # when: '"Reboot is required" in needs_restarting'
