---
- name: run Ansible setup module and display output
  hosts: all
  tasks:
  - name: run you mf
    ansible.builtin.setup:
     filter: 
      - 'ansible_hostname'
      - 'ansible_distribution'
    register: setup_result
  - name: Show results
    ansible.builtin.debug:
     var: setup_result