---
- name: Start W11 VM
  hosts: localhost
  connection: local
  become: true  # Optional: needed if libvirt requires root
  tasks:
    - name: Start a virtual machine
      community.libvirt.virt:
        name: W11  # <-- replace with your actual VM name
        state: running
