---
- hosts: all
  become: yes
  tasks:
  - name: update cache
    ansible.builtin.apt:
     update_cache: yes
     
  - name: Inform what updates we have available
    ansible.builtin.shell:
     cmd:  apt list --upgradable -a
    register: updates_needed
     
  - name: Update all installed packages using APT module
    ansible.builtin.apt:
      name: '*'
      state: latest
    register: apt_update_status

  - name: Remove packages not needed anymore
    ansible.builtin.apt:
      autoremove: yes

#  - name: Reboot when packages were updated
#    reboot:
#      post_reboot_delay: 60
#    when: apt_update_status.changed


  - name: Check if a reboot is required
    stat: path=/var/run/reboot-required get_md5=no
    register: reboot_flag

  - name: Inform its done
    uri:
      url: "http://192.168.1.89:70/zajcnet-notif"
      method: POST
      body: "{{ ansible_hostname }} patched: \n {{ updates_needed.stdout_lines }}"
    when: apt_update_status.changed

  - name: Reboot notice if needed
    uri:
      url: "http://192.168.1.89:70/zajcnet-notif"
      method: POST
      body: "{{ ansible_hostname }} needs a reboot mate"
    when: reboot_flag.stat.exists == true
#    reboot:
#      reboot_timeout: 300
