---
- hosts: yum
  become: yes

  tasks:
  - name: Update all installed packages using YUM module
    yum:
      name: '*'
      state: latest
      update_cache: yes
      update_only: yes
    register: yum_update_status

  - name: Remove packates not needed anymore
    yum:
      autoremove: yes

  - name: Reboot when packages were updated
    reboot:
    when: yum_update_status.changed

- hosts: apt
  become: yes
  tasks:
  - name: update cache
    ansible.builtin.apt:
     update_cache: yes
  - name: Update all installed packages using APT module
    ansible.builtin.apt:
      name: '*'
      state: latest
    register: apt_update_status

  - name: Remove packages not needed anymore
    ansible.builtin.apt:
      autoremove: yes

  - name: Reboot when packages were updated
    reboot:
      post_reboot_delay: 60
    when: apt_update_status.changed